INSERT INTO MAASLAK.PRZYNALEZNOSCI (GŁOWNA, GATUNEK_NAZWA, ZESPOL_ID) VALUES (null, 'Ambient', 11);
INSERT INTO MAASLAK.PRZYNALEZNOSCI (GŁOWNA, GATUNEK_NAZWA, ZESPOL_ID) VALUES (null, 'Thrash Metal', 9);
INSERT INTO MAASLAK.PRZYNALEZNOSCI (GŁOWNA, GATUNEK_NAZWA, ZESPOL_ID) VALUES (null, 'Ambient', 5);